#!/bin/bash
#sudo umount -l /mnt/data
#sudo mount -t tmpfs -o size=1024m tmpfs /mnt/data
sudo docker service create --name sf-exporter \
    -e SYSLOG_HOST=localhost \
    -e SYSLOG_PORT=514 \
    -e NODE_IP=10.1.0.159 \
    -e INTERVAL=15 \
    -e DIR=/mnt/data \
    --mount type=bind,source=/mnt/data,destination=/mnt/data \
    sf-exporter:latest
