#!/bin/bash
#./monitor.py --host=10.1.0.159 --port=9000 --accesskey=RDPVTNKW2UXY9KQV8XPE --secretkey=cR/MMkDEYdB14sD4WgjAZ9gX4IaMG0HdMEOkGeg4
#sudo umount -l /mnt/data
#sudo mount -t tmpfs -o size=1024m tmpfs /mnt/data
sudo docker service create --name trace_collector \
    -e HOST=10.1.0.159 \
    -e INTERVAL=1 \
    --secret minio_access_key \
    --secret minio_secret_key \
    --mount type=bind,source=/mnt/data,destination=/mnt/data \
    tracecollector:latest
